# This is the default configuration for RespawnX by SirBlobman
# Made for version ${pluginVersion}

# Debug Mode. Should be false unless you are testing a bug.
debug-mode: false

# How many ticks should RespawnX wait before automatically respawning players?
# 20 ticks is one second.
# Default: 1
delay: 1

# Should a permission be required to automatically respawn a player?
# Default: false (no)
require-permission: false

# If 'require-permission' is set to true, what permission is required?
# This permission is NOT given to OPs by default.
# Default: "respawnx.respawn.automatic"
permission: "respawnx.respawn.automatic"

# This is a list of worlds that RespawnX will fail to work in
# Worlds are case sensitive, therefore "world" is not the same as "wOrLd"
#
# Default:
# - "minigame1"
# - "MiNiGaMe2"
disabled-world-list:
  - "minigame1"
  - "MiNiGaMe2"

# Set this to true if you want the 'disabled-world-list' to be
# a list of enabled worlds instead.
# Default: false
disabled-world-list-inverted: false

# Which commands should be executed when a player respawns?
# Set it to [] to disable
#
# Default:
# - "give {player} rotten_flesh 1 0"
respawn-commands:
  - "give {player} rotten_flesh 1 0"

respawn-near-death:
  # Should players respawn near the location they died?
  # Default: false
  enabled: false

  # How close to their death location should they respawn?
  # The distance is a circular radius of blocks
  # Default: 1.0
  radius: 1.0

  # Should players be teleported to the regular respawn location
  # if the area around their death location is unsafe?
  # Current unsafe locations are only detected by lava blocks.
  # Default: true
  prevent-unsafe-respawn: true
