# This is the default configuration for RespawnX
# RespawnX is made by SirBlobman
# Made for version ${bukkit.plugin.version}

# How long should RespawnX wait before automatically respawning players?
# The delay is in ticks
#
# Default: 1
delay: 1

# Should a permission be required to automatically respawn a player?
#
# Default: false (no)
require permission: false

# If 'require permission' is set to true, what permission is required?
#
# Default: "respawnx.respawn.automatic"
permission: "respawnx.respawn.automatic"

respawn near death:
  # Should players respawn near the location they died?
  #
  # Default: false
  enabled: false
  
  # How close to their death location should they respawn?
  # The distance is a circular radius of blocks
  #
  # Default: 1
  radius: 1